Property.create!(name: "130 Piper Knowle Road", empty: false)
Property.create!(name: "89 Fairwell Road", empty: false)
Property.create!(name: "3 Glaisdale Road", empty: false)
Property.create!(name: "5 Scurfield Road", empty: true)
Property.create!(name: "110 Fairwell Road", empty: false)
